package Enums;

public enum TipoInimigosEnum {
    ZUMBI("Lento, porém resistente", 1, 10),
    GOBLIN("Rápido e fraco", 1, 5),
    DRAGAO("Forte e poderoso, cospe fogo", 10, 20),
    ESQUELETO("Moderadamente resistente e armado", 2, 8),
    LADRAO("Ágil e sorrateiro, rouba itens", 3, 7),
    OGRO("Grande e muito forte, mas lento", 5, 12),
    VAMPIRO("Rápido, se regenera com o sangue", 7, 15),
    FANTASMA("Incorpóreo, difícil de acertar", 3, 10),
    SLIME("Se divide ao ser atacado", 1, 4),
    DEMONIO("Extremamente poderoso, causa medo", 12, 20),
    SERPENTE_GIGANTE("Ataca com veneno e rapidez", 5, 13),
    LOBO("Ataca em matilha, rápido e feroz", 2, 6),
    ARANHA_GIGANTE("Usa veneno e teia para capturar inimigos", 4, 10),
    GOLEM_DE_PEDRA("Resistente a ataques físicos, lento", 8, 16),
    GOLEM_DE_FOGO("Imune a fogo, ataca com chamas", 9, 17),
    GOLEM_DE_GELO("Pode congelar o oponente", 8, 16),
    TRITAO("Domina batalhas subaquáticas", 5, 10),
    SUCUBO("Atrai inimigos com charme e drena energia", 6, 12),
    HARPYA("Ataca a longa distância com voo rápido", 4, 9),
    CYCLOPE("Monstro gigante com um olho, força bruta", 7, 15),
    MINOTAURO("Meio-humano, meio-touro, usa força", 6, 14),
    WYVERN("Criatura voadora que lança ácido", 9, 18),
    MÚMIA("Ser ressuscitado, resistente a danos", 4, 10),
    ELEMENTAL_DE_FOGO("Entidade formada por fogo puro", 8, 17),
    ELEMENTAL_DE_AGUA("Usa ataques baseados em água", 7, 14),
    ELEMENTAL_DE_TERRA("Manipula o solo ao seu redor", 8, 16),
    ELEMENTAL_DE_AR("Rápido e intangível, ataca com ventos", 6, 12),
    VESPA_GIGANTE("Ataca em enxames e possui veneno mortal", 2, 8),
    KRAKEN("Monstro colossal do mar, ataca navios", 12, 20),
    MEDUSA("Transforma inimigos em pedra com seu olhar", 10, 18),
    CENTAURO("Guerreiro metade homem, metade cavalo", 5, 10),
    BEHOLDER("Criatura flutuante com múltiplos olhos mágicos", 10, 19),
    VERMIS_GIGANTE("Monstro subterrâneo que ataca de surpresa", 6, 13),
    DRACOLICH("Dragão morto-vivo com poderes necromânticos", 15, 20),
    ESPIRITO_DO_VENTO("Ataca com rajadas de vento cortante", 4, 9),
    ETTIN("Gigante de duas cabeças, força monstruosa", 9, 17),
    HOBGOBLIN("Versão mais forte e organizada do goblin", 4, 10),
    BANSHEE("Espírito que emite gritos mortais", 8, 16),
    GHUL("Criatura carniceira que se alimenta de mortos", 3, 8),
    FENRIR("Lobo gigante, ancestral dos lobos", 10, 18),
    QUIMERA("Criatura com cabeças de leão, bode e dragão", 8, 16),
    GÁRGULA("Estátua viva que ataca à noite", 5, 12),
    HIDRA("Criatura com várias cabeças regenerativas", 9, 18),
    BOGGART("Criatura mutante que se transforma em medos", 3, 8),
    URSO_GIGANTE("Forte e resistente, ataca com brutalidade", 5, 12),
    ESPIRITO_DA_FLORESTA("Protege florestas com magia natural", 6, 13),
    RATOS_MUTANTES("Atacam em hordas, transmitem doenças", 1, 5),
    ABOMINACAO("Criatura costurada de várias partes", 6, 14),
    OGRO_MAGO("Ogros que dominaram o uso de magia", 9, 17),
    DEMONIO_INFERNAL("Demônio vindo do submundo com chamas eternas", 12, 20),
    ORC_BERSERKER("Guerreiro orc em fúria, destrói tudo à frente", 7, 15),
    CAVALEIRO_NEGRO("Cavaleiro maldito com armadura impenetrável", 8, 16),
    LICH("Mago morto-vivo que domina a necromancia", 12, 20),
    ESPECTRO("Fantasma que drena vida e energia", 5, 12),
    JABUTI_GIGANTE("Criatura lenta, mas com armadura natural", 2, 8),
    GIGANTE_DE_GELO("Gigante que domina as tempestades de neve", 9, 17),
    VAMPIRO_ANCIÃO("Vampiro muito antigo, extremamente poderoso", 15, 20),
    MANTICORA("Criatura com corpo de leão e cauda venenosa", 8, 16),
    IFREET("Demônio do fogo que causa destruição por onde passa", 10, 18),
    DJINN("Espírito do vento com poder de manipular o ar", 7, 15),
    GOBLIN_XAMA("Lidera tribos goblins com magia sombria", 3, 9),
    YETI("Criatura peluda das montanhas geladas", 6, 12),
    BASILISCO("Criatura reptiliana com olhar mortal", 9, 17),
    CARCINOS("Caranguejo gigante com pinças mortais", 4, 9),
    RATO_GIGANTE("Causa caos em cidades, rápido e furtivo", 1, 5),
    GRIFO("Criatura com corpo de leão e asas de águia", 7, 14),
    OGRO_DUAS_CABEÇAS("Mais forte e mais inteligente que um ogro comum", 8, 16),
    DEMONIO_DA_SOMBRA("Entidade que ataca a partir das sombras", 9, 17),
    VERME_CAOTICO("Criatura aberrante com múltiplas bocas", 4, 9),
    LAGARTO_DE_LAVA("Criatura das profundezas vulcânicas", 6, 12),
    FURIA("Espírito vingativo que ataca com velocidade", 5, 10),
    GIGANTE_DE_MONTANHA("Monstro gigantesco que habita os picos", 9, 18),
    SIRENE("Criatura do mar que encanta marinheiros com sua voz", 4, 9),
    TROLL("Regenera rapidamente, especialmente em cavernas", 5, 10),
    ARANHA_VENENOSA("Criatura letal que usa veneno e armadilhas de teia", 3, 8),
    TITAN("Criatura colossal com poder inimaginável", 15, 20),
    ESPIRITO_DE_LAVA("Ser feito de lava, incendeia tudo que toca", 7, 15),
    DRUIDA_CORROMPIDO("Usa a natureza de maneira maligna para atacar", 6, 12),
    ANJO_CAIDO("Ser celestial corrompido, extremamente poderoso", 12, 20),
    MONSTRO_ABISAL("Criatura das profundezas do abismo", 10, 18),
    SENHOR_DA_GUERREIRO("Líder de uma horda, usa estratégias de combate", 8, 16),
    LOBISOMEN("Humano que se transforma em lobo feroz", 7, 14),
    SERPENTE_DAS_ARENAS("Criatura venenosa de desertos e arenas", 5, 12),
    ESPIRITO_VINGATIVO("Fantasma que busca vingança com poderes aumentados", 8, 15),
    GIGANTE_CAVERNOSO("Monstro de cavernas com força bruta", 9, 17),
    ESPÍRITO_NATURAL("Entidade que controla elementos naturais", 6, 13),
    AGENTE_SOMBRA("Espião furtivo que se esconde nas sombras", 4, 10),
    CRIATURA_COSMICA("Ser alienígena com poderes misteriosos", 12, 20),
    MONSTRO_METALICO("Criatura robótica com poderosos ataques físicos", 7, 15),
    DRAGAO_DE_GELO("Dragão que domina o frio e a neve", 11, 18),
    DRAGAO_DOURADO("Dragão majestoso com habilidades mágicas", 13, 20),
    DRAGAO_DAS_TREVAS("Dragão sombrio que domina as trevas", 12, 20),
    REI_GOBLIN("Chefe dos goblins, muito mais poderoso", 6, 14),
    IMP("Demônio menor com truques mágicos", 3, 7),
    ESPIRITO_MILITAR("Espírito de um soldado antigo, habilidoso em combate", 5, 12),
    AMULETO_VIVO("Amuleto mágico com vontade própria", 8, 15),
    TROLL_VERDE("Troll com força aumentada e habilidades de regeneração", 7, 14),
    MORCEGO_GIGANTE("Criatura voadora que ataca com batedores de morcego", 4, 10),
    RAPOSA_DE_FOGO("Criatura ágil com chamas que ataca com sua cauda", 5, 12),
    GIGANTE_DA_FLOR("Gigante das florestas com poderes de planta", 7, 14),
    VENTO_EFÊMERO("Ser do vento que causa tempestades", 6, 12),
    CAMPEAO_ORC("Orc líder de batalha, muito mais forte", 8, 16),
    ALBINO_VAMPIRO("Vampiro raro com habilidades adicionais", 10, 18),
    GUARDIAO_DE_TERRA("Criatura feita de rochas e terra", 6, 13),
    SERPENTE_DE_AR("Serpente aérea com veneno e habilidades de voo", 5, 12),
    AVATAR_DA_DEUSA("Ser divino com poderes de uma deusa", 14, 20),
    URSO_RABIOSO("Urso com ataques devastadores e grande resistência", 5, 12),
    TITÃ_DAS_FLAMAS("Criatura colossal feita de fogo", 12, 20),
    CRIATURA_LOST("Ser perdido em dimensões alternadas", 8, 16),
    PIRATA_ESQUELETO("Espírito de um pirata antigo, muito habilidoso", 6, 13),
    ESPIRITO_MALIGNO("Entidade sombria que busca causar caos", 7, 15),
    FANTASMA_ANTIGO("Fantasma de um ser antigo, com habilidades de necromancia", 9, 17),
    CRENDE_DE_TERRA("Ser deformado que manipula rochas", 6, 13),
    INIMIGO_MISTICO("Criatura mágica com poderes arcânicos", 8, 16),
    DEUS_GIGANTE("Ser imenso com habilidades divinas", 14, 20),
    DEMONIO_SILENCIOSO("Demônio que se esconde na escuridão", 10, 18),
    QUIMERA_DAS_NUVENS("Criatura que voa entre as nuvens com habilidades tempestivas", 9, 17),
    SER_NATURAL("Entidade que controla elementos naturais com habilidade", 7, 15),
    REI_DE_FERRO("Criatura de ferro com grande força e resistência", 8, 16),
    MONSTRO_VORTEX("Criatura que manipula vórtices e tempestades", 9, 18),
    MONSTRO_INFECCIOSO("Criatura que espalha doenças e infecções", 6, 13),
    REI_CAVEIRA("Líder esquelético que comanda exércitos mortos-vivos", 11, 20),
    ESPIRITO_SECRETO("Fantasma que se esconde e ataca de surpresa", 5, 12),
    DEMONIO_ANTIGO("Demônio ancestral com grande poder e sabedoria", 12, 20),
    SERPENTE_MISTICA("Serpente com habilidades mágicas e veneno poderoso", 7, 15),
    SENHOR_DE_MONTANHAS("Criatura dominante das montanhas com força imensa", 8, 16),
    PORTAL_ABERTO("Ser criado a partir de um portal dimensional", 10, 18),
    ESPIRITO_DAS_TREVAS("Entidade das trevas com habilidades de medo", 9, 17),
    ELEMENTAL_DE_METAL("Criatura feita de metal com habilidades pesadas", 8, 16),
    GUARDIAO_VELOZ("Ser que protege com velocidade e agilidade", 6, 13),
    MONSTRO_REGENERATOR("Criatura que regenera rapidamente e causa dano constante", 7, 14),
    LOUCO_DE_RUBIS("Ser deformado que manipula pedras preciosas", 6, 12),
    DRAGAO_DO_CEUS("Dragão celestial com habilidades poderosas", 13, 20),
    SENHOR_DE_RUINAS("Criatura que domina ruínas e destroços", 7, 14),
    ESPIRITO_ANCIANO("Entidade antiga com vasto conhecimento e poder", 10, 18),
    SENHOR_DOS_RATOS("Líder de uma horda de ratos", 4, 10),
    DEMONIO_VASTO("Entidade demoníaca com vasto poder e domínio", 12, 20),
    CRIATURA_ESCURIDAO("Criatura que vive nas sombras e manipula escuridão", 8, 16);

    private final String descricao;
    private final int nivelMinimo;
    private final int nivelMaximo;

    TipoInimigosEnum(String descricao, int nivelMinimo, int nivelMaximo) {
        this.descricao = descricao;
        this.nivelMinimo = nivelMinimo;
        this.nivelMaximo = nivelMaximo;
    }

    public String getDescricao() {
        return descricao;
    }

    public int getNivelMinimo() {
        return nivelMinimo;
    }

    public int getNivelMaximo() {
        return nivelMaximo;
    }
}
